#
# Jekyll Configuration file for "Develop mobile apps with C# and Azure"

title: &title "Develop mobile apps with C# and Azure"
email: "photoadrian@outlook.com"
description: >- # this means to ignore newlines until "baseurl:"
  Build amazing mobile experiences with the power of the Azure Cloud and
  the latest in .NET technologies - C# and MAUI.
tagline: Build amazing mobile experiences with .NET and Azure
locale: en-US
baseurl: "" 
url: "" 

collections:
  book:
    output: true

defaults:
  - scope:
      path: ""
      type: "book"
    values:
      layout: "book"

###############################################################################################
#
# THEME Settings
#
###############################################################################################
theme:
  logo: /assets/site-logo.svg
  
favicon:
  tile_color: "#da532c"
  theme_color: "#ffffff"
  
###############################################################################################
#
# SEO Configuration: See https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#
###############################################################################################
author: adrianhall

# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234

logo: /assets/site-logo.png

seo:
  name: *title
  type: Book

social:
  name: Adrian Hall
  links:
    - https://twitter.com/FizzyInTheHall
    - https://linkedin.com/in/adrianhall1
    - https://github.com/adrianhall

twitter:
  username: FizzyInTheHall
  card: summary

# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
#   facebook: 1234

###############################################################################################
#
# Build Settings
#
###############################################################################################
plugins:
  - jekyll-seo-tag

sass:
  implementation: sass-embedded
  style: compressed
  sourcemap: development
