site_name: Develop Cloud Connected Mobile Apps with C# and Microsoft Azure
site_url: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/
repo_url: https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure
repo_name: GitHub
edit_uri: ""
site_author: Adrian Hall
copyright: >-
  Copyright &copy; 2017-2023 Adrian Hall<span id="consent-marker"> -
  <a href="#__consent">Change cookie settings</a></span>
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of the book and whether users find what 
      they're searching for. With your consent, you're helping us to make the 
      book better.  We do not and will not sell your information - ever.
    actions:
      - accept
      - reject
      - manage
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adrianhall
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/adrianhall1/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/photoadrian
extra_css:
  - assets/stylesheets/extra.css
theme: 
  name: material
  custom_dir: theme
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font:
    text: Open Sans
    code: Source Code Pro
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - glightbox
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences 
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Chapter 1:
    - chapter1/index.md
    - Your First App - PC Edition: chapter1/pc-intro.md
    - Your First App - Mac Edition: chapter1/mac-intro.md
  - tools.md
    # - Chapter 2 - Authentication:
    #     - Concepts: chapter2/authconcepts.md
    #     - Authentication in the Backend: chapter2/backend.md
    #     - Enterprise Authentication: chapter2/enterprise.md
    #     - Social Authentication: chapter2/social.md
    #     - Debugging Authentication: chapter2/debugging.md
    #     - Custom Authentication: chapter2/custom.md
    #     - Claims and Authorization: chapter2/authorization.md
    #     - Tokens in Real Apps: chapter2/realworld.md
    #     - Best Practices: chapter2/bestpractices.md
    # - Chapter 3 - Data Access and Offline Sync:
    #     - Concepts: chapter3/dataconcepts.md
    #     - Implementing Table Controllers: chapter3/server.md
    #     - Data Projection and Queries: chapter3/projection.md
    #     - The Mobile Client: chapter3/client.md
    #     - Relationships: chapter3/relationships.md
    #     - The Domain Manager: chapter3/domainmgr.md
    # - Chapter 4 - Server Side Code:
    #     - Options for Server Code: chapter4/options.md
    #     - Custom HTTP Endpoints: chapter4/custom.md
    #     - WebJobs: chapter4/webjobs.md
    #     - Functions: chapter4/functions.md
    #     - Recipes: chapter4/recipes.md
    # - Chapter 5 - Push Notifications:
    #     - Concepts: chapter5/concepts.md
    #     - Android Push: chapter5/android.md
    #     - iOS Push: chapter5/ios.md
    #     - Windows Push: chapter5/windows.md
    #     - Push Recipes: chapter5/recipes.md
    # - Chapter 6 - Combining Web and Mobile Apps:
    #     - MVC Applications: chapter6/mvc.md
    #     - jQuery Applications: chapter6/jquery.md
    #     - Angular Applications: chapter6/angular.md
    #     - React Applications: chapter6/react.md
    # - Chapter 7 - Other Useful Services:
    #     - Useful Azure Services: chapter7/services.md
    #     - Azure Search: chapter7/search.md
    #     - Media Services: chapter7/media.md
    # - Chapter 8 - Developing An App:
    #     - The Development Environment: chapter8/developing.md
    #     - Testing your Application: chapter8/testing.md
    # - Chapter 9 - Going to Production:
    #     - Repeatable Deployments: chapter9/arm.md
    #     - Safe Deployments: chapter9/appsvc.md
    #     - Monitoring and Troubleshooting: chapter9/monitoring.md
    # - Xamarin Forms Tips: xamarin_tips.md
    # - Android Developer Notes: android_appendix.md
    # - Visual Studio Extensions: vs_extensions.md
    # - References: references.md
    # - Credits: credits.md
