edit_uri: ""

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - smarty
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/links.md
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - awesome-pages
  - exclude:
      glob:
        - includes/*.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - search:
      indexing: full

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Open Sans
    code: Source Code Pro
  icon: 
    logo: material/library
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefered-color-scheme: dark)"
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - _extras/site.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _extras/site.js
