name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-exclude mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
